### ISSUE TITLE
How long until an update?

### ISSUE THREAD

**Issue by ghost** [YellowPhoenix18/VersionAPI#1]
Minecraft is for kikes

**Comment by YellowPhoenix18** [comment]
Rwg work also without VersionAPI, you can open your server and add VersionAPI, when it gets its update

**Comment by ghost** [comment]
.

**Comment by YellowPhoenix18** [comment]
Than you have to wait, maxbe this evening, maybe at the weekend, currently im ver busy

**Comment by ghost** [comment]
.

**Comment by YellowPhoenix18** [comment]
Of course, but RWG`s Main-Feature is not that Actionbar and it is ckearly described, that you have to use VersionAPI, this Software will be updatet, but when I dont have time I cant ise thw time, you know :)

**Comment by YellowPhoenix18** [comment]
Update is out, 1.12 should be supported now ;)

With best regards,
YellowPhoenix18
