### ISSUE TITLE
1.4 Major Bug

### ISSUE THREAD

**Issue by ghost** [YellowPhoenix18/VersionAPI#2]
Was so happy that you updated this but the entire plugin is bugged. Instead of saying the biome on the actionbar it spams the chat. (Picture attached)

![bug](https://user-images.githubusercontent.com/30607647/28901196-95f8ab6e-77c4-11e7-9504-b59809b91470.png)

**Comment by YellowPhoenix18** [comment]
Oh, sorry. I`ll do another Update today

**Comment by YellowPhoenix18** [comment]
Fixed
